services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
      - type: bind
        source: ./database/
        target: /var/etc/database
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev