#pragma once

#include <pebble.h>
#include "../sprites/player_sprites.h"

uint8_t DEFAULT_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11111111, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00,
    #endif
};

uint8_t PLAYER_ONE_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11110000, 0b11111111, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00,
    #endif
};

uint8_t DEFAULT_SPRITE_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11111111, 0b11010000, 0b11100000, 0b11000011, 0b11000111, 0b11000100, 0b11001000,  0b11111111, 0b11000011, 0b11001010, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b11, 0b00, 0b10, 0b11, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00,
    #endif
};

uint8_t OLD_DEFAULT_SPRITE_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11111111, 0b11000000, 0b11010101, 0b11000001, 0b11000111, 0b11010000, 0b11110000,  0b11111100, 0b11010101, 0b11101010, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b11, 0b00, 0b10, 0b11, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00,
    #endif
};

uint8_t HAIR_PALETTES[][16] = {
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
};

uint8_t SHIRT_PALETTES[][16] = {
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_WHITE_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
};

uint8_t PANTS_PALETTES[][16] = {
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
};

uint8_t SHOE_PALETTES[][16] = {
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
        {COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
};

// #define DEFAULT_DEFAULT 0

// const uint8_t DEFAULT_DATA[] = {
//     // vram tile start, width, height
//     0, 1, 2, // default
// };

// static uint16_t load_default(GBC_Graphics *gbc_graphics, uint8_t vram_bank, uint8_t vram_start_offset, uint8_t palette_num, uint8_t *num_sprites, const uint8_t **sprite_data) {
//     // Load default tilesheet
//     uint16_t num_loaded_tiles = load_tilesheet(gbc_graphics, RESOURCE_ID_DATA_DEFAULT_TILESHEET, 0, vram_start_offset, vram_bank);

//     // Load default palette
//     GBC_Graphics_set_sprite_palette_array(gbc_graphics, palette_num, DEFAULT_PALETTES[0]);

//     // Set number of sprites
//     *num_sprites = 1;

//     // Set sprite data
//     *sprite_data = DEFAULT_DATA;
    
//     return num_loaded_tiles;
// }

// #define PLAYER_ONE_1_UP 0
// #define PLAYER_ONE_2_RIGHT 1
// #define PLAYER_ONE_3_DOWN 2
// #define PLAYER_ONE_4_LEFT 3

// const uint8_t PLAYER_ONE_DATA[] = {
//     // vram tile start, width, height
//     0, 1, 2, // 1_up
//     6, 1, 2, // 2_right
//     12, 1, 2, // 3_down
//     18, 1, 2, // 4_left
// };

// static uint16_t load_player_one(GBC_Graphics *gbc_graphics, uint8_t vram_bank, uint8_t vram_start_offset, uint8_t palette_num, uint8_t *num_sprites, const uint8_t **sprite_data) {
//     // Load player_one tilesheet
//     uint16_t num_loaded_tiles = load_tilesheet(gbc_graphics, RESOURCE_ID_DATA_PLAYER_ONE_TILESHEET, 0, vram_start_offset, vram_bank);

//     // Load player_one palette
//     GBC_Graphics_set_sprite_palette_array(gbc_graphics, palette_num, PLAYER_ONE_PALETTES[0]);

//     // Set number of sprites
//     *num_sprites = 4;

//     // Set sprite data
//     *sprite_data = PLAYER_ONE_DATA;
    
//     return num_loaded_tiles;
// }

// #define NUM_SPRITE_GROUPS 2

// uint16_t (*LOAD_SPRITE_GROUP[2])(GBC_Graphics *gbc_graphics, uint8_t vram_bank, uint8_t vram_start_offset, uint8_t palette_num, uint8_t *num_sprites, const uint8_t **sprite_data) = {
//     load_default,
//     load_player_one,
// };

    