#pragma once

#include <pebble.h>
#include "../sprites/player_sprites.h"
#include "../../pebble-gbc-graphics-advanced/pebble-gbc-graphics-advanced.h"

uint8_t DEFAULT_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11111111, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00,
    #endif
};

uint8_t PLAYER_ONE_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11110000, 0b11111111, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00, 0b00,
    #endif
};

uint8_t DEFAULT_SPRITE_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11111111, 0b11010000, 0b11100000, 0b11000011, 0b11000111, 0b11000100, 0b11001000,  0b11111111, 0b11000011, 0b11001010, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b11, 0b00, 0b10, 0b11, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00,
    #endif
};

uint8_t OLD_DEFAULT_SPRITE_PALETTE[16] = {
    #if defined(PBL_COLOR)
        0b11000000, 0b11000000, 0b11111111, 0b11000000, 0b11010101, 0b11000001, 0b11000111, 0b11010000, 0b11110000,  0b11111100, 0b11010101, 0b11101010, 0b11000000, 0b11000000, 0b11000000, 0b11000000,
    #else
        0b00, 0b00, 0b11, 0b00, 0b00, 0b00, 0b11, 0b00, 0b10, 0b11, 0b00, 0b11, 0b00, 0b00, 0b00, 0b00,
    #endif
};

#if defined(PBL_COLOR)

uint8_t HAIR_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
};

uint8_t SHIRT_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_ACCENT, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
};

uint8_t PANTS_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
};

uint8_t SHOE_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_RED_MAJOR, COLORS_RED_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_ORANGE_MAJOR, COLORS_ORANGE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_YELLOW_MAJOR, COLORS_YELLOW_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_GREEN_MAJOR, COLORS_GREEN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_BLUE_MAJOR, COLORS_BLUE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_PURPLE_MAJOR, COLORS_PURPLE_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_PINK_MAJOR, COLORS_PINK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_GRAY_MAJOR, COLORS_GRAY_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_BLACK_MAJOR, COLORS_BLACK_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
};

#else
uint8_t HAIR_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, GBC_COLOR_BLACK, GBC_COLOR_GRAY, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
};

uint8_t SHIRT_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, GBC_COLOR_BLACK, GBC_COLOR_GRAY, GBC_COLOR_WHITE, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL,},
};

uint8_t PANTS_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, COLORS_NULL, COLORS_NULL, GBC_COLOR_BLACK, GBC_COLOR_BLACK, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
};

uint8_t SHOE_PALETTES[][16] = {
    {COLORS_BASE, COLORS_SKIN_MAJOR, COLORS_SKIN_MINOR, GBC_COLOR_BLACK, GBC_COLOR_BLACK, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, COLORS_NULL, },
};

#endif // if defined(PBL_COLOR)
