#pragma once
#include "../pebble-gbc-graphics-advanced/pebble-gbc-graphics-advanced.h"

// Scrool window
#define SCROLL_FONT FONT_KEY_GOTHIC_18
#define SCROLL_TEXT_LEN 200

#define USERNAME_MAX_LEN 20
#define SETTINGS_KEY 1

// Gameplay
#define MAX_PLAYERS 20

// Graphics
#define FRAMERATE 8
#define FRAME_DURATION (1000 / FRAMERATE)
#define NUM_VRAMS 2
#define NUM_BACKGROUNDS 1
#define SCREEN_TILE_WIDTH 18
#define SCREEN_TILE_HEIGHT 18
#define SCREEN_PIXEL_WIDTH (SCREEN_TILE_WIDTH * GBC_TILE_WIDTH)
#define SCREEN_PIXEL_HEIGHT (SCREEN_TILE_HEIGHT * GBC_TILE_HEIGHT)
#if defined (PBL_ROUND)
    #define SCREEN_BOUNDS GRect(18, 18, SCREEN_PIXEL_WIDTH, SCREEN_PIXEL_HEIGHT)
#else
    #define SCREEN_BOUNDS GRect(0, STATUS_BAR_LAYER_HEIGHT + 4, SCREEN_PIXEL_WIDTH, SCREEN_PIXEL_HEIGHT)
#endif

// Background
#define BG_VRAM 0
#define BG_TILE_WIDTH 90
#define BG_TILE_HEIGHT 90
#define BG_NUM_TILES (BG_TILE_WIDTH * BG_TILE_HEIGHT)
#define BG_PIXEL_WIDTH (BG_TILE_WIDTH * GBC_TILE_WIDTH)
#define BG_PIXEL_HEIGHT (BG_TILE_HEIGHT * GBC_TILE_HEIGHT)
#define BG_PLAYER_OFFSET_X ((BG_PIXEL_WIDTH / 2) - SCREEN_PIXEL_WIDTH / 2)
#define BG_PLAYER_OFFSET_Y ((BG_PIXEL_HEIGHT / 2) - SCREEN_PIXEL_WIDTH / 2)

// Players
#define PLAYER_VRAM 1
#define PLAYER_SPRITE_TILE_WIDTH 2 // 2 tiles, 16 px
#define PLAYER_SPRITE_TILE_HEIGHT 3 // 3 tiles, 24 px
#define PLAYER_SPRITE_NUM_TILES (PLAYER_SPRITE_TILE_WIDTH * PLAYER_SPRITE_TILE_HEIGHT)
#define PLAYER_ONE_NUM_SPRITES 8
#define PLAYER_ONE_NUM_TILES (PLAYER_SPRITE_NUM_TILES * PLAYER_ONE_NUM_SPRITES)
#define PLAYER_SPRITE_WIDTH (PLAYER_SPRITE_TILE_WIDTH * GBC_TILE_WIDTH)
#define PLAYER_SPRITE_HEIGHT (PLAYER_SPRITE_TILE_HEIGHT * GBC_TILE_HEIGHT)
#define PLAYER_STEP_SIZE 16
#define PLAYER_SUB_STEP_SIZE 4
#define PLAYER_WALK_FRAME_COUNT 4
#define PLAYER_SPRITE_SCREEN_X_OFFSET (((GBC_SPRITE_OFFSET_X + (SCREEN_PIXEL_WIDTH / 2 - (PLAYER_SPRITE_WIDTH / 2))) / GBC_TILE_WIDTH) * GBC_TILE_WIDTH)
#define PLAYER_SPRITE_SCREEN_Y_OFFSET (((GBC_SPRITE_OFFSET_Y + (SCREEN_PIXEL_HEIGHT / 2 - (PLAYER_SPRITE_HEIGHT / 2))) / GBC_TILE_HEIGHT) * GBC_TILE_HEIGHT)
#define PLAYER_MIN_X (-SCREEN_PIXEL_WIDTH * 2)
#define PLAYER_MAX_X (SCREEN_PIXEL_WIDTH * 2)
#define PLAYER_MIN_Y (-SCREEN_PIXEL_WIDTH * 2)
#define PLAYER_MAX_Y (SCREEN_PIXEL_WIDTH * 2)
#define PLAYER_SCREEN_MIN_OFFSET_X (-(SCREEN_PIXEL_WIDTH / 2 + PLAYER_SPRITE_WIDTH / 2))
#define PLAYER_SCREEN_MAX_OFFSET_X ((SCREEN_PIXEL_WIDTH / 2 + PLAYER_SPRITE_WIDTH / 2))
#define PLAYER_SCREEN_MIN_OFFSET_Y (-(SCREEN_PIXEL_HEIGHT / 2 + PLAYER_SPRITE_HEIGHT / 2))
#define PLAYER_SCREEN_MAX_OFFSET_Y ((SCREEN_PIXEL_HEIGHT / 2 + PLAYER_SPRITE_HEIGHT / 2))
#define PLAYER_FONT FONT_KEY_GOTHIC_14

// Menu Items
// - Main menu
#define MAIN_MENU_NUM_ITEMS 6
#define MENU_ITEM_INFO 0
#define MENU_ITEM_SETTINGS 1
#define MENU_ITEM_USERS 2
#define MENU_ITEM_FRIEND_REQUESTS 3
#define MENU_ITEM_HELP 4
#define MENU_ITEM_LOGOUT 5
// - Settings menu
#define SETTINGS_MENU_NUM_ITEMS 1
#define MENU_ITEM_TILT 0

// Tilt
// - Calibration
#define TILT_THRESHOLD 150

// Window popup
#define POPUP_SLIDE_DURATION 500
#define POPUP_EXIST_DURATION 2000
#define POPUP_FONT FONT_KEY_GOTHIC_18
#define POPUP_HEIGHT 42
#define POPUP_BORDER_THICKNESS 2
#define POPUP_TEXT_LEN 60
#define POPUP_TEXT_Y_OFFSET -2
#define POPUP_CORNER_RADIUS 10
#define MESSAGE_QUEUE_LEN 10

// Confirmation menu
#define CONF_TEXT_LEN 40
#define CONF_FONT FONT_KEY_GOTHIC_24_BOLD
#define CONF_TEXT_INSET 4